### ISSUE TITLE
Wishlist: Font size preference

### ISSUE THREAD

**Issue by callegar** [no-go/AnotherRSS#10]
I think that it could be useful to have an option to choose the font size. Zoom with reflowing would be even better, but probably much more expensive to implement.

**Comment by alltagshack** [comment]
I will try to implement it in the next days, but I have to fix my bicycle first :-/

**Comment by callegar** [comment]
I totally agree that the bike goes first!

**Comment by alltagshack** [comment]
bike is still buggy. But in version 1.8 you can change the image size and font size, now. New images will be cached in the new size. The old images are scaled and this make scrolling a bit non-smooth :cry:
