### ISSUE TITLE
[wishlist] A dark theme

### ISSUE THREAD

**Issue by malteb247** [no-go/AnotherRSS#15]
Thanks for the great work, I really appreciate it. Simple and clean, well done!

I would love to see a dark theme with true black background and white foreground (e.g. as seen in Twidere).

The current night-mode doesn't realy fit me needs, as the dark red text isn't readable both by day and night. :)

Device: Nexus 5X
Android: 7.1.2
ARSS: 1.7 (latest I found on F-Droid)

**Comment by alltagshack** [comment]
I think, many person does not like the red text. In Version v1.9 it is more like twidere

**Comment by malteb247** [comment]
Where can I find it?
I saw also people mentioning 1.8, but the latest release I can find is 1.7.

**Comment by alltagshack** [comment]
fdroid is not very fast. google play store is a bit faster. I place an signed APK (the some signed version linke on the play store) [here - get the app](https://no-go.github.io/AnotherRSS/#get-the-app) or direct [here](https://raw.githubusercontent.com/no-go/AnotherRSS/master/app/app-release.apk)
