### ISSUE TITLE
[feature request] opml import/export

### ISSUE THREAD

**Issue by x2k13** [no-go/AnotherRSS#19]
Please add a feature to import/export feeds via .opml files

**Comment by alltagshack** [comment]
hi x2k13,
I am sorry, but I do not want to add this feature.

Import and export needs file access permissions. I think, there are to many apps with to much permissions. Many german people are very careful and will not install a reader with that permissions.

My App is FOSS (free open source software). Feel free to make a branch and make your own app with all the feature you want to add.
