### ISSUE TITLE
Use add/remove buttons instead of 13 input fields

### ISSUE THREAD

**Issue by ghost** [no-go/AnotherRSS#2]
Instead of having 13 input fields, you should be able to add/remove as many feeds as you whish.

**Comment by alltagshack** [comment]
hi. After filling the lines and "store" them, 5 new free lines are added. :-D

**Comment by ghost** [comment]
That's great, thank you. Still, using add/remove buttons would increase the usability.
Or maybe do it like this: Present only one field, as soon as the last field isn't empty, add another field and as soon as the second last field and the last one are empty, remove the last input field.

**Comment by alltagshack** [comment]
a (+) button is a good idea. I will try do do that :-D
