### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by ghost** [no-go/AnotherRSS#30]
Hello, @no-go I want to contribute in "AnotherRSS" so i want to design a new logo for "AnotherRSS" and it's free.

I hope you like it. If you like it, I will send you to pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my design

Contact me on facebook for fast delivery 
https://www.facebook.com/waqasanwar68

**Comment by alltagshack** [comment]
Sorry, I like the current logo and am not looking for another one at the moment.

Thanks to @subchannel13i for that hint:

> I appreciate your effort in making open source apps look better, but opening issues with 1. capital letters as title and 2. links to Facebook are not considered best practice.


@abdulmalikkhan655  and @waqasanwar94 please check your git issue bots. They are the same!
