### ISSUE TITLE
More sounds

### ISSUE THREAD

**Issue by alltagshack** [no-go/AnotherRSS#4]
The "Riing" makes me crazy :-(

But: This App did not get access to the filesystem!!!

**Comment by ghost** [comment]
Maybe something from freesound? 

- https://freesound.org/people/TheGertz/sounds/235911/
- https://freesound.org/people/mickleness/sounds/269189/
- https://freesound.org/people/UnderlinedDesigns/sounds/328243/

are using a public domain license for example

**Comment by alltagshack** [comment]
I will try it. But the last one is realy noisy :-S

**Comment by alltagshack** [comment]
I add some new sounds. You can disable sound or choose the default one, too.
