### ISSUE TITLE
sound preview

### ISSUE THREAD

**Issue by alltagshack** [no-go/AnotherRSS#6]
it would be great to hear the selected sound before choosing it.

**Comment by rbchinchen** [comment]
This is the current behaviour of the default clock app, could the source of that provide any guidance? 

https://android.googlesource.com/platform/packages/apps/DeskClock/+/master/src/com/android/deskclock/ringtone/RingtonePickerActivity.java

In that file around the 380 mark you'll find the code relating to the preview sound functions.

**Comment by alltagshack** [comment]
I think, I need about 8 hours to add the feature. I have similar code to play sounds. But I have flu and next week my uni starts :-(

**Comment by alltagshack** [comment]
I add it in v2.15 on commit https://github.com/no-go/AnotherRSS/commit/94d0ab691196ab7116eba20dc3140af59adc20f6

:-D
