### ISSUE TITLE
Add setting for tap behaviour

### ISSUE THREAD

**Issue by ghost** [no-go/AnotherRSS#7]
As said in #5, tapping on a feed does nothing in portrait mode, what about you include a setting which allows for setting that behaviour?
So maybe open up the website externally, do nothing, mark as read,...

**Comment by alltagshack** [comment]
A "long press" should select an item on Android. I add the context menu to the "select" event. It is strange, that this does not work on your phone.

Setting up a tap-behaviour should fix it for you, but it changes a big and ugly part in my source code. I try to implement it in the next 4 hours.

**Comment by alltagshack** [comment]
In version 1.7 there is a "tap behaviour" in the preferences. I hope, this fix your problem - or is a good workaround.

I forgot the "do nothing" option X-) but "open right-hand (landscape)" is the default option and very similar on portrait mode.
